# Generated by Django 4.2.6 on 2023-10-28 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_authgroup_delete_authgrouppermissions_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='detalleasistencia',
            table='detalle_asistencia',
        ),
    ]
